### ISSUE TITLE
Not all people from the "names.csv" file are being matched

### ISSUE THREAD

**Issue by georginaeaton** [moj-analytical-services/coffee_roulette_pairs#7]
@ms130 - myself and Aidan have found that we are getting a couple of matches that are missing from the unwanted pairs file (which is currently the replacement for getting the matches instead of the "round.csv"  file). I think we both have around or above 30 names if that's useful for any testing.

**Comment by aidanmews** [comment]
@ms130 thanks for modifying. I've just run through 45 names with only 19 pairs being returned so something still not quite right!

**Comment by georginaeaton** [comment]
I am still missing a pair when using 54 names (but same as Aidan, I assume this is because I am not referencing the dev branch?)

**Comment by ms130** [comment]
> @ms130 how do you get the code to use the dev branch of the package?

@georginaeaton you can run the following to install from the dev branch:
`remotes::install_github('moj-analytical-services/coffee_roulette_pairs', ref = 'dev')`

**Comment by ms130** [comment]
Hi @aidanmews and @aidanmews thanks for bearing with me here! Please try reinstalling from the `dev` branch. I've added lots of helpful error messages now. 

The `save_pairs` function will now stop with an error message explaining what to do, if an incomplete round is generated. This can happen when the number of wanted pairs gets quite large combined to the number of pairs it's possible to generate from the names provided.

Simply try running the function again, and it'll re-randomise and have another go at generating a complete round. Keep trying until you get a complete round, otherwise remove some unwanted pairs, or give up

Does that make sense?
